# Generated by Django 4.2.1 on 2023-05-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expirience',
            field=models.IntegerField(default=0, max_length=99999),
        ),
    ]
