# Generated by Django 4.2.1 on 2023-05-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_expirience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expirience',
            field=models.IntegerField(default=0),
        ),
    ]
