# Generated by Django 4.2.1 on 2023-05-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='photo',
            field=models.ImageField(null=True, upload_to='exam_photo'),
        ),
    ]
