# Generated by Django 4.2.1 on 2023-05-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_exam_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, unique_for_date=True),
        ),
    ]
